### ISSUE TITLE
Cross language support?

### ISSUE THREAD

**Issue by IsraeliK33** [shane-mason/essential-generators#2]
Cross language support?
I speak Russian and Hebrew, its not clear how to add languages, thanks.

**Comment by shane-mason** [comment]
This can be done by generating a new corpus and new text and word models for the generator to use. There are a couple of simple tools in the test directory to help with this. Here are the basic steps:

1.  Build a new corpus by putting a bunch of text in the language you want to use into and name this file 'corpus.txt' 
2.  Build text models from the corpus by running 'build_text_model.py'
3.  Build word models by running 'build_word_model.py'

This process will overwrite the default models (essential_generators/markov_textgen.json and essential_generators/markov_wordgen.json) with new models built on the languages in your corpus.txt file.

Note that this will NOT change the bahaviour of Statistic word generation since it is based on statistics found in English text. You can easily edit essential_generators/statistic_wordgen.py and replace the letters, word length and bigram frequencies with those of the language of your choice.

Here are the tools in the test directory:

**build_corpus.py** - Retrieves specified articles from wikipedia to use when training the models. Default output is 'corpus.txt'. **build_text_model.py** - Uses corpus.txt to output markov_textgen.json   ##as the text model for sentences and paragraphs. **build_word_model.py** - Uses corpus.txt to output markov_wordgen.json as the word model (for words, email, domains etc)

**Comment by shane-mason** [comment]
See above comment - closing issue as resolved.
